Change mono font to IBM Plex Mono
garden-co/classic-jazz pull request #405
Opened 2024-09-17 16:04 UTC by trishalim

<img width="431" alt="image" src="https://github.com/user-attachments/assets/d45044fb-0600-4a2b-ac7b-5fd67e879018">

2024-09-17 16:40 UTC, aeplay requested changes
Looking very good overall, IBM plex is almost perfect but I'm not a fan of the `{}` (forgot they had so much character)

Please may you change it to Commit Mono? And then we can compare with the next Vercel deploy (just commit on top of this PR)

Thanks!

2024-09-18 12:32 UTC, trishalim commented
> Looking very good overall, IBM plex is almost perfect but I'm not a fan of the `{}` (forgot they had so much character)
> 
> Please may you change it to Commit Mono? And then we can compare with the next Vercel deploy (just commit on top of this PR)
> 
> Thanks!

I agree the `{}` was too much. Looks better now.

I can't see the vercel preview because I don't have access.

2024-09-18 15:47 UTC, aeplay approved these changes

2024-09-18 15:47 UTC, trishalim commented
@aeplay If you're happy with this, feel free to merge.

2024-09-18 15:47 UTC, merged