chore(sync): move all the optimisticKnownStates update logic inside PeerKnownStates
garden-co/classic-jazz pull request #646
Opened 2024-10-29 20:54 UTC by gdorsi

In this PR I'm encapsulating all the peers optimisticKnownStates updates in a class called PeerKnownStates.

The idea is to make possible to subscribe to the `optimisticKnownState` to check the sync status of a coValue.

I've used this new "feature" to improve the create account command on jazz-run by replacing the `sleep` with a `waitForSync` function.

2024-10-29 20:55 UTC, gdorsi commented on packages/cojson/src/tests/PeerState.test.ts
> -    });
Removed this test because it wasn't actually useful

2024-10-29 21:29 UTC, aeplay commented
✨

2024-10-29 21:29 UTC, aeplay commented
changeset pls (even though it doesn't functionally change jazz-run account create - but it is more than a temporary fix now)

2024-10-29 21:35 UTC, gdorsi commented on packages/jazz-run/src/accountCreate.ts
> +const accountCreate = Command.make(
Most of the code here has been extracted from `./index.ts`

2024-10-29 21:35 UTC, gdorsi commented on packages/jazz-run/src/accountCreate.ts
> +            ]));
This is the actual change.

Before this was done with an `Effect.sleep(2000)`

2024-10-29 21:35 UTC, gdorsi commented on packages/jazz-run/src/accountCreate.ts
> +        const unsubscribe = peerState?.optimisticKnownStates.subscribe((id, peerKnownState) => {
@aeplay 

Tried to make a non-optimistic known state but it seems to me that the current exchanged messages aren't enough to collect a fully up-to-date known state.

We will need that to fully proceed with #307 so I think that would be good to start a discussion around this issue.

2024-10-29 21:35 UTC, gdorsi commented on packages/jazz-run/src/accountCreate.ts
> +            // Spawn a second peer to double check that the account is fully synced
@aeplay 

Is this comment correct?

2024-10-29 21:45 UTC, gdorsi commented
Changeset added

2024-10-30 09:21 UTC, aeplay commented on packages/jazz-run/src/accountCreate.ts
> +            // Spawn a second peer to double check that the account is fully synced
yes

2024-10-30 09:23 UTC, aeplay requested changes
It's not a big deal, but for the sake of clarity in the per-package changelogs, please may you delete the changeset and then create two change sets, one for cojson (subscribe to peer state) and one for jazz-run (improve account create). Thank you!

Everything else LGTM

2024-10-30 18:50 UTC, gdorsi commented
@aeplay changeset splitted!

2024-10-30 20:05 UTC, merged