Rearrange feature sections
garden-co/classic-jazz pull request #671
Opened 2024-11-01 10:56 UTC by trishalim

2024-11-01 13:25 UTC, aeplay commented
@trishalim before you go to far with the illustrations, I don't think the two-way state binding feature is as good as the others to have there.

Not because it's wrong (it's correct), but because people have a very strong "two-way binding bad" preconception since react, so best to just trick them into it and talk about something else here

Plus it's not really an "additional feature" it's more like an inherent feature of the CoValues.

Will think of something to replace it with!

2024-11-01 13:26 UTC, trishalim commented
@aeplay Great. I was just about to ask you

2024-11-01 13:27 UTC, trishalim commented
@aeplay what do you think about the new placement for e2e?

2024-11-01 13:37 UTC, aeplay commented
> @aeplay what do you think about the new placement for e2e?

good place, but could be more prominent! I think it might even deserve more text since it is one of the most unique aspects of Jazz (happy to help with the copy)

2024-11-01 13:37 UTC, aeplay commented
And what do you think about server workers as an "extra feature"? We don't really mention it anywhere except in the diagram and it is typically one of the biggest surprises when explaining Jazz

2024-11-01 13:43 UTC, trishalim commented
@aeplay ok. Can you write some copy? Any idea for the illustration?

I will try to make e2e more prominent. And feel free to suggest more words for it.

2024-11-01 13:48 UTC, aeplay commented
**Server workers**

Subscribe to Jazz state and update existing databases or third-party APIs. Or expose an HTTP API that mutates Jazz state.

2024-11-01 13:52 UTC, aeplay commented
Illustration: how about a variant of the hero illustration? Something like this (see Figma) as a very rough sketch

<img width="427" alt="Screenshot 2024-11-01 at 13 51 46" src="https://github.com/user-attachments/assets/b5ecb6ad-1f91-4447-bff0-342c1e349d62">

2024-11-01 14:05 UTC, trishalim commented
@aeplay I pushed a commit for e2e 🤔

2024-11-01 14:08 UTC, aeplay commented
The big icon helps!

more words for e2ee:

**End-to-end encrypted and tamper-proof**

Instead of trusting a centralised backend to enforce permissions, Jazz uses public-key cryptography. Your edits are encrypted and signed on-device, verifiable by everyone and readable only by users and servers explicitly given access. The syncing server never sees your data in plaintext.

I know it's long but thoughts?

2024-11-01 14:09 UTC, aeplay commented
Also wdyt about "Taking collaboration a step further" -> "Making secure collaboration the default" ?

2024-11-01 14:12 UTC, trishalim commented
I think the collaboration section is mostly about the reader, writer, or admin roles. Why do you want to emphasize "secure"?

2024-11-01 14:12 UTC, aeplay commented
Plus one more thought for the local-first section:

Offline first + support for bad connections deserves it's own tile.

Here we can talk about our opinion that even in a well connected world offline support and especially support for weak connections is really important and that local-first apps deal with this much more gracefully

2024-11-01 14:13 UTC, trishalim commented
> Offline first + support for bad connections deserves it's own tile.

Yes totally 💯

2024-11-01 14:14 UTC, trishalim commented
You wanted to make a bold claim about "local first is the best way to build apps" and maybe it's appropriate here

2024-11-01 14:14 UTC, aeplay commented
> I think the collaboration section is mostly about the reader, writer, or admin roles. Why do you want to emphasize "secure"?

ok how about "Collaboration as a first-class concept"

2024-11-01 14:18 UTC, aeplay commented
> You wanted to make a bold claim about "local first is the best way to build apps" and maybe it's appropriate here

The whole page is about that... I think we're doing a good job of saying that

2024-11-01 14:35 UTC, trishalim commented
<img width="658" alt="image" src="https://github.com/user-attachments/assets/ac72ef91-16e0-4cc6-95fc-c525337a892f">

2024-11-01 14:41 UTC, aeplay commented
> <img alt="image" width="658" src="https://private-user-images.githubusercontent.com/13136861/382309326-ac72ef91-16e0-4cc6-95fc-c525337a892f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzIzMjQsIm5iZiI6MTczMDQ3MjAyNCwicGF0aCI6Ii8xMzEzNjg2MS8zODIzMDkzMjYtYWM3MmVmOTEtMTZlMC00Y2M2LTk1ZmMtYzUyNTMzN2E4OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE0NDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzZjMzBiZDc1NzhmNTkxMTczNTNjM2FmY2Y4NzNkMmJhNzczYmJkOTI5Nzk0ZDliMzI4YTBhYzAzODU5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7u59ARjfHM9SYThsqhldyE8sK8eljmOkTdL2_TDo6AY">

nice simplification, but the arrow on the left needs to be reversed, it's HTTP request coming in

2024-11-01 14:43 UTC, trishalim commented
<img width="659" alt="image" src="https://github.com/user-attachments/assets/14c8d0f6-fc2d-4ce3-890c-33dcce1e64d5">

2024-11-01 15:26 UTC, trishalim commented
I added more text to e2ee and the server worker illustration

2024-11-01 15:30 UTC, trishalim commented
It would be nice to have social proof from SA1 related to the collaboration features

2024-11-01 15:33 UTC, aeplay commented
Lol you weren't kidding with HUGE.

I'd say with it having more text it's prominent enough even with a small icon - you can make it look the same as the features in "Why local-first?" for consistency. Wdyt?

social proof from SA1:

"We were building our app as a single-player experience first, planning to add team and org features much later. But because we built it with Jazz, we had that from day one. All we needed to add was an invite button."

- Lead Developer @ Invoice Radar

2024-11-01 15:45 UTC, trishalim commented
So much space on the right 🤔
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/7ee3198e-0f61-4f72-8ff4-ceb45d3c026a">

2024-11-01 15:52 UTC, aeplay commented
> So much space on the right 🤔 <img alt="image" width="1311" src="https://private-user-images.githubusercontent.com/13136861/382328971-7ee3198e-0f61-4f72-8ff4-ceb45d3c026a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzYyOTksIm5iZiI6MTczMDQ3NTk5OSwicGF0aCI6Ii8xMzEzNjg2MS8zODIzMjg5NzEtN2VlMzE5OGUtMGY2MS00ZjcyLThmZjQtY2ViNDVkM2MwMjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE1NDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzY1YWRmMmM3NDcwODYwMWU5YmUwMTdhZDc1ZGI2M2ZhNDNjZjdjZWY2YzFiYTRmYjdlN2Y4YzdhM2UzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CQGlwwwLeab7DJ2E86vx3kZXA4H_pBsStLFoCUUKUaQ">

<img width="338" alt="Screenshot 2024-11-01 at 15 52 18" src="https://github.com/user-attachments/assets/81b20587-3485-4cf8-9149-938c3f864154">

another diagram will fix it!
(see Figma, you'll be able to make it nicer)

2024-11-01 16:03 UTC, trishalim commented
@aeplay I think we have enough diagrams 🙈 I'll think of some other option

2024-11-01 16:10 UTC, aeplay commented
> @aeplay I think we have enough diagrams 🙈 I'll think of some other option

@trishalim something like the "random encrypted letters" as in the https://evervault.com hero?

2024-11-01 16:12 UTC, trishalim commented
Cool! I like it

It'd be great if we can cut down the description by one sentence

2024-11-01 16:15 UTC, aeplay commented
> Cool! I like it
> 
> It'd be great if we can cut down the description by one sentence

how about

End-to-end encrypted and tamper-proof
The syncing server never sees your data in plaintext.

Instead of trusting a centralised backend, Jazz uses public-key cryptography. Your edits are encrypted and signed on-device, verifiable by everyone and readable only to those given access.

2024-11-01 16:16 UTC, aeplay commented
@trishalim edited

2024-11-01 16:58 UTC, trishalim commented
Updated e2e text and illustration
I'm pretty happy with this

2024-11-01 18:46 UTC, trishalim commented
Since we have 4 items here, I am trying out a different layout

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/0da9ae74-7bf2-4cfd-aeda-4172680a844d">

Idk what goes on the right yet, but I'm thinking we could somehow emphasize that it works offline.

2024-11-04 11:40 UTC, trishalim commented
@aeplay I'm keeping the local-first section simple for now. I just checked https://www.instantdb.com/ and realized they have a very similar section, and they show small demos each. Maybe we can do a demo as well.

2024-11-04 16:41 UTC, aeplay requested changes
Great work!!

A bunch of small suggestions:

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/EncryptionSection.tsx
> +    return (
I'm assuming the lock icon is somewhere in here...

Please may we use https://lucide.dev/icons/lock-keyhole and make it look like one of the feature-chips higher up? (Light blue bg with blue lines in bright mode)

Right now the solid-filled icon looks a bit out of place.

And then you can also use the same icon in the hero for the E2EE feature hint.

Thank you!

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                get progressive image loading, super fast blur preview, and
```suggestion
                get progressive image up & downloading, super fast blur preview, and
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                Subscribe to Jazz state and update existing databases or
```suggestion
                Expose an HTTP API that mutates Jazz state.
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                third-party APIs. Or expose an HTTP API that mutates Jazz state.
```suggestion
                Or subscribe to Jazz state and update existing databases or third-party APIs.
```

(Changing the order to correspond how you would read the diagram)

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                Plug and play different kinds of auth like WebAuthN (Touch ID,
```suggestion
                Plug and play different kinds of auth like Passkeys (Touch ID,
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/EncryptionSection.tsx
> +                            everyone and readable only to those given access.
```suggestion
                            everyone and readable only by those given access.
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                                Easy setup, no configuration needed.
```suggestion
                                Instant setup, no configuration needed.
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                            "Blob storage",
```suggestion
                            "Data & blob storage",
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                            "Data storage",
```suggestion
                            "Global sync",
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                            View full pricing
```suggestion
                            View free tier & pricing
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/FeaturesSection.tsx
> +                        You can rely on us, or{" "}
```suggestion
                        Or{" "}
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/HeroSection.tsx
> +        icon: KeyRoundIcon,
https://lucide.dev/icons/lock-keyhole please

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/LocalFirstFeaturesSection.tsx
> +                    instantly. Just mutate data the JSON object. No API calls
```suggestion
                    instantly. Just mutate data. No API calls
```

2024-11-04 16:41 UTC, aeplay commented on homepage/homepage/components/home/LocalFirstFeaturesSection.tsx
> +                    Adding multiplayer is as easy as sharing state with other
```suggestion
                    Adding multiplayer is as easy as sharing synced data with other
```

2024-11-04 18:06 UTC, trishalim commented
@aeplay Thanks for the feedback. Can you please check again

2024-11-04 18:16 UTC, aeplay requested changes
Final super annoying request: please make the lock icon on top of the random letters as small as the icons in "why local-first"

Thank you!

2024-11-04 18:26 UTC, trishalim commented
No worries. It's small now

2024-11-05 09:31 UTC, aeplay approved these changes

2024-11-05 09:31 UTC, aeplay commented on homepage/homepage/app/(home)/page.tsx
>                  <Testimonial name="Serious Adopter #4" role="Technical Founder">
```suggestion
                <Testimonial name="Spreadsheet app (stealth)" role="CTO">
```

2024-11-05 09:31 UTC, aeplay commented on homepage/homepage/app/(home)/page.tsx
> +                <Testimonial name="Serious Adopter #1" role="Lead Developer">
```suggestion
                <Testimonial name="Invoice Radar" role="Technical Founder">
```

2024-11-05 09:46 UTC, aeplay commented on homepage/homepage/components/home/CollaborationPrivate.mdx
> +Message.create({
```suggestion
Message.create(
```

2024-11-05 09:46 UTC, aeplay commented on homepage/homepage/components/home/CollaborationPrivate.mdx
> +  text: ...,
```suggestion
  { text: ... },
```

2024-11-05 09:46 UTC, aeplay commented on homepage/homepage/components/home/CollaborationPrivate.mdx
> +  owner: me
```suggestion
  { owner: me }
```

2024-11-05 09:46 UTC, aeplay commented on homepage/homepage/components/home/CollaborationPrivate.mdx
> +});
```suggestion
);
```

2024-11-05 09:46 UTC, aeplay commented on homepage/homepage/components/home/CollaborationPublic.mdx
> +group.addMember("everyone", "writer");
```suggestion
group.addMember("everyone", "writer");

Chat.create([], { owner: group })
```

2024-11-05 09:58 UTC, merged