feat: pressing cmd+j in a jazz app exports the jazz account to inspector
garden-co/classic-jazz pull request #842
Opened 2024-11-21 15:32 UTC by pax-k

2024-11-25 14:53 UTC, aeplay requested changes
Left a suggestion for making the confirmation consequences clearer.

Please may you put the secret into the hash part of the URL for the inspector? That way it never gets shared with the server hosting the inspector.

2024-11-25 14:53 UTC, aeplay commented on packages/jazz-tools/src/utils/export-account-inspector.ts
> +          "Are you sure you want to export your account to the inspector?",
```suggestion
          "Are you sure you want to inspect your account using inspector.jazz.tools? This lets anyone with the secret inspector URL read your data and impersonate you.",
```

2024-11-25 15:30 UTC, pax-k commented
> Left a suggestion for making the confirmation consequences clearer.
> 
> Furthermore
> 
> * Please may you put the secret into the hash part of the URL for the inspector? That way it never gets shared with the server hosting the inspector.
> * Could you always enable the shortcut if the app's url contains "allowJazzInspector"? That way we can instruct users to enable it even in prod if the devs didn't

Done.

If a user opens an URL like `http://localhost:5173/#/vault?allowJazzInspector`, then pressing `cmd+j` will show the confirmation and will redirect the user.

2024-11-26 17:25 UTC, aeplay requested changes
Thank you!

Sorry, last requests:

- please can you move the shortcut logic / function to jazz-browser? It doesn't really make sense in jazz-tools
- please add a changeset that describes the feature well for the changelog!

2024-12-04 18:57 UTC, gdorsi commented on packages/jazz-browser/src/utils/export-account-inspector.ts
> +  console.log(url.hash);
```suggestion
```

2024-12-04 18:58 UTC, gdorsi commented on packages/jazz-browser/src/utils/export-account-inspector.ts
> +  if (url.hash.includes("allowJazzInspector")) {
**suggestion:** what about adding `|| process.env.NODE_ENV !== 'production'` to enable this on dev?

2024-12-04 18:58 UTC, gdorsi commented on packages/jazz-browser/src/utils/export-account-inspector.ts
> +  if (url.hash.includes("allowJazzInspector")) {
**suggestion:** what about adding `|| process.env.NODE_ENV !== 'production'` to enable this on dev?

2024-12-04 19:00 UTC, gdorsi commented on packages/jazz-browser/src/utils/export-account-inspector.ts
> +  if (url.hash.includes("allowJazzInspector")) {
```suggestion
  if (url.hash.includes("allowJazzInspector") || process.env.NODE_ENV === "development") {
```

**suggestion:** what about enabling the shortcut by default on dev?

2024-12-04 19:00 UTC, gdorsi commented on packages/jazz-browser/src/utils/export-account-inspector.ts
> +  if (url.hash.includes("allowJazzInspector")) {
cc @anselm

2024-12-11 08:33 UTC, merged